#!/bin/bash

CONTAINER="codesvault_phptest"
PLUGIN_PATH="/var/www/html/wp-content/plugins/deep-search"

# Usage: ./test [command] [args]
# Commands:
#   (no args)     - Sync files and run Pest
#   copy <path>   - Copy a file/folder from host to container
#   pull <path>   - Copy a file/folder from container to host
#   pest [args]   - Run Pest with optional arguments
#   exec <cmd>    - Execute a command in the container
#   sync-vendor   - Copy vendor from container to vendor-test for IDE support

case "$1" in
    sync-vendor)
        rm -rf ./vendor-test
        docker cp "$CONTAINER:$PLUGIN_PATH/vendor" ./vendor-test
        echo "Synced vendor to vendor-test for IDE support"
        ;;
    copy)
        if [ -z "$2" ]; then
            echo "Usage: ./test copy <path>"
            exit 1
        fi
        docker cp "$2" "$CONTAINER:$PLUGIN_PATH/$2"
        docker exec -u root "$CONTAINER" chown -R docker:docker "$PLUGIN_PATH/$2"
        echo "Copied $2 to container"
        ;;
    pull)
        if [ -z "$2" ]; then
            echo "Usage: ./test pull <path>"
            exit 1
        fi
        docker cp "$CONTAINER:$PLUGIN_PATH/$2" "./$2"
        echo "Pulled $2 from container"
        ;;
    pest)
        shift
        if [ -t 0 ]; then
            docker exec -it "$CONTAINER" bash -c "cd $PLUGIN_PATH && ./vendor/bin/pest $*"
        else
            docker exec "$CONTAINER" bash -c "cd $PLUGIN_PATH && ./vendor/bin/pest $*"
        fi
        ;;
    exec)
        shift
        if [ -t 0 ]; then
            docker exec -it "$CONTAINER" bash -c "cd $PLUGIN_PATH && $*"
        else
            docker exec "$CONTAINER" bash -c "cd $PLUGIN_PATH && $*"
        fi
        ;;
    *)
        # Default: sync and run pest
        docker cp -q ./tests "$CONTAINER:$PLUGIN_PATH/"
        docker cp -q ./app "$CONTAINER:$PLUGIN_PATH/"
        docker exec -u root "$CONTAINER" chown -R docker:docker "$PLUGIN_PATH/tests" "$PLUGIN_PATH/app"
        if [ -t 0 ]; then
            docker exec -it "$CONTAINER" bash -c "cd $PLUGIN_PATH && ./vendor/bin/pest $*"
        else
            docker exec "$CONTAINER" bash -c "cd $PLUGIN_PATH && ./vendor/bin/pest $*"
        fi
        ;;
esac

exit 0
